services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=g73_lanches
    networks:
      - app-network

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=techchallenge
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - app-network

  g73-order-api:
    image: igorramos/g73-order-api:production
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      PORT: '8080'
      AUTHORIZER_URL: 'https://fzmgicpudl.execute-api.us-east-1.amazonaws.com/v1/authorize'
      POSTGRES_HOST: 'postgres'
      POSTGRES_DB: 'g73_lanches'
      POSTGRES_PORT: '5432'
      POSTGRES_SSLMODE: "?sslmode=disable"
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      PAYMENT_URL: 'http://localhost:8081/v1/paymentOrder'
      DEFAULT_TIMEOUT: '500ms'
      MIGRATIONS_PATH: './migrations'
      ORDER_EVENTS_BROKER_URL: 'amqp://techchallenge:admin123@rabbitmq:5672/'
      ORDER_EVENTS_TOPIC: 'order_events'
      ORDER_EVENTS_PAID_QUEUE: 'orders_payment_queue'
      ORDER_EVENTS_READY_QUEUE: 'orders_ready_queue'
      ORDER_EVENTS_IN_PROGRESS_DESTINATION: 'orders.inprogress'
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  g73-payment-api:
    image: igorramos/g73-payment-api:production
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      ENVIRONMENT: "local"
      CONFIG_DIR_PATH: "../configs"
      ORDER_EVENTS_BROKER_URL: "amqp://techchallenge:admin123@rabbitmq:5672/"
    networks:
      - app-network
    depends_on:
      - dynamodb-local
  
  g73-kitchen-api:
    image: igorramos/g73-kitchen-api:production
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      PORT: "8082"
      ORDER_TABLE: "Kitchen"
      ORDER_TABLE_ENDPOINT": "http://localhost:8000/"
      ORDER_EVENTS_BROKER_URL: "amqp://techchallenge:admin123@rabbitmq:5672/"
      ORDER_EVENTS_TOPIC: "order_events"
      ORDER_EVENTS_IN_PROGRESS_QUEUE: "orders_inprogress_queue"
      ORDER_EVENTS_READY_QUEUE: "ORDER_EVENTS_READY_QUEUE"
      ORDER_READY_EVENTS_DESTINATION: "orders.ready"
    networks:
      - app-network
    depends_on:
      - dynamodb-local

networks:
  app-network:
    driver: bridge