apiVersion: apps/v1
kind: Deployment
metadata:
  name: g73-payment-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g73-payment-api
  template:
    metadata:
      labels:
        app: g73-payment-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: g73-payment-api
          image: igorramos/g73-payment-api:production
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: ENVIRONMENT
              value: "prod"
            - name: CONFIG_DIR_PATH
              value: "../configs"
            - name: ORDER_EVENTS_BROKER_URL
              value: "amqp://techchallenge:admin123@rabbitmq:5672/"

          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
